#!/usr/bin/env bash
# Qompass AI Qonfig Git Submodule Install
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
set -e
CONFIG="qonfig.yaml"
QONFIG_DIR="qonfig"
QONFIG_BIN="bin/qonfig"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${BASEDIR}"
git submodule update --init --recursive "${QONFIG_DIR}"
"${BASEDIR}/${QONFIG_DIR}/${QONFIG_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
